// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package auth0.proxies;

public class Key
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject keyMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Auth0.Key";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Alg("Alg"),
		Kty("Kty"),
		Use("Use"),
		N("N"),
		E("E"),
		Kid("Kid"),
		X5t("X5t"),
		Key_Keys("Auth0.Key_Keys"),
		X5c_Key("Auth0.X5c_Key");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Key(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Auth0.Key"));
	}

	protected Key(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject keyMendixObject)
	{
		if (keyMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Auth0.Key", keyMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Auth0.Key");

		this.keyMendixObject = keyMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Key.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static auth0.proxies.Key initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return auth0.proxies.Key.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static auth0.proxies.Key initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new auth0.proxies.Key(context, mendixObject);
	}

	public static auth0.proxies.Key load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return auth0.proxies.Key.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Alg
	 */
	public final java.lang.String getAlg()
	{
		return getAlg(getContext());
	}

	/**
	 * @param context
	 * @return value of Alg
	 */
	public final java.lang.String getAlg(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Alg.toString());
	}

	/**
	 * Set value of Alg
	 * @param alg
	 */
	public final void setAlg(java.lang.String alg)
	{
		setAlg(getContext(), alg);
	}

	/**
	 * Set value of Alg
	 * @param context
	 * @param alg
	 */
	public final void setAlg(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String alg)
	{
		getMendixObject().setValue(context, MemberNames.Alg.toString(), alg);
	}

	/**
	 * @return value of Kty
	 */
	public final java.lang.String getKty()
	{
		return getKty(getContext());
	}

	/**
	 * @param context
	 * @return value of Kty
	 */
	public final java.lang.String getKty(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Kty.toString());
	}

	/**
	 * Set value of Kty
	 * @param kty
	 */
	public final void setKty(java.lang.String kty)
	{
		setKty(getContext(), kty);
	}

	/**
	 * Set value of Kty
	 * @param context
	 * @param kty
	 */
	public final void setKty(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String kty)
	{
		getMendixObject().setValue(context, MemberNames.Kty.toString(), kty);
	}

	/**
	 * @return value of Use
	 */
	public final java.lang.String getUse()
	{
		return getUse(getContext());
	}

	/**
	 * @param context
	 * @return value of Use
	 */
	public final java.lang.String getUse(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Use.toString());
	}

	/**
	 * Set value of Use
	 * @param use
	 */
	public final void setUse(java.lang.String use)
	{
		setUse(getContext(), use);
	}

	/**
	 * Set value of Use
	 * @param context
	 * @param use
	 */
	public final void setUse(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String use)
	{
		getMendixObject().setValue(context, MemberNames.Use.toString(), use);
	}

	/**
	 * @return value of N
	 */
	public final java.lang.String getN()
	{
		return getN(getContext());
	}

	/**
	 * @param context
	 * @return value of N
	 */
	public final java.lang.String getN(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.N.toString());
	}

	/**
	 * Set value of N
	 * @param n
	 */
	public final void setN(java.lang.String n)
	{
		setN(getContext(), n);
	}

	/**
	 * Set value of N
	 * @param context
	 * @param n
	 */
	public final void setN(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String n)
	{
		getMendixObject().setValue(context, MemberNames.N.toString(), n);
	}

	/**
	 * @return value of E
	 */
	public final java.lang.String getE()
	{
		return getE(getContext());
	}

	/**
	 * @param context
	 * @return value of E
	 */
	public final java.lang.String getE(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.E.toString());
	}

	/**
	 * Set value of E
	 * @param e
	 */
	public final void setE(java.lang.String e)
	{
		setE(getContext(), e);
	}

	/**
	 * Set value of E
	 * @param context
	 * @param e
	 */
	public final void setE(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String e)
	{
		getMendixObject().setValue(context, MemberNames.E.toString(), e);
	}

	/**
	 * @return value of Kid
	 */
	public final java.lang.String getKid()
	{
		return getKid(getContext());
	}

	/**
	 * @param context
	 * @return value of Kid
	 */
	public final java.lang.String getKid(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Kid.toString());
	}

	/**
	 * Set value of Kid
	 * @param kid
	 */
	public final void setKid(java.lang.String kid)
	{
		setKid(getContext(), kid);
	}

	/**
	 * Set value of Kid
	 * @param context
	 * @param kid
	 */
	public final void setKid(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String kid)
	{
		getMendixObject().setValue(context, MemberNames.Kid.toString(), kid);
	}

	/**
	 * @return value of X5t
	 */
	public final java.lang.String getX5t()
	{
		return getX5t(getContext());
	}

	/**
	 * @param context
	 * @return value of X5t
	 */
	public final java.lang.String getX5t(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.X5t.toString());
	}

	/**
	 * Set value of X5t
	 * @param x5t
	 */
	public final void setX5t(java.lang.String x5t)
	{
		setX5t(getContext(), x5t);
	}

	/**
	 * Set value of X5t
	 * @param context
	 * @param x5t
	 */
	public final void setX5t(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String x5t)
	{
		getMendixObject().setValue(context, MemberNames.X5t.toString(), x5t);
	}

	/**
	 * @return value of Key_Keys
	 */
	public final auth0.proxies.Keys getKey_Keys() throws com.mendix.core.CoreException
	{
		return getKey_Keys(getContext());
	}

	/**
	 * @param context
	 * @return value of Key_Keys
	 */
	public final auth0.proxies.Keys getKey_Keys(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		auth0.proxies.Keys result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Key_Keys.toString());
		if (identifier != null)
			result = auth0.proxies.Keys.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Key_Keys
	 * @param key_keys
	 */
	public final void setKey_Keys(auth0.proxies.Keys key_keys)
	{
		setKey_Keys(getContext(), key_keys);
	}

	/**
	 * Set value of Key_Keys
	 * @param context
	 * @param key_keys
	 */
	public final void setKey_Keys(com.mendix.systemwideinterfaces.core.IContext context, auth0.proxies.Keys key_keys)
	{
		if (key_keys == null)
			getMendixObject().setValue(context, MemberNames.Key_Keys.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Key_Keys.toString(), key_keys.getMendixObject().getId());
	}

	/**
	 * @return value of X5c_Key
	 */
	public final auth0.proxies.X5c getX5c_Key() throws com.mendix.core.CoreException
	{
		return getX5c_Key(getContext());
	}

	/**
	 * @param context
	 * @return value of X5c_Key
	 */
	public final auth0.proxies.X5c getX5c_Key(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		auth0.proxies.X5c result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.X5c_Key.toString());
		if (identifier != null)
			result = auth0.proxies.X5c.load(context, identifier);
		return result;
	}

	/**
	 * Set value of X5c_Key
	 * @param x5c_key
	 */
	public final void setX5c_Key(auth0.proxies.X5c x5c_key)
	{
		setX5c_Key(getContext(), x5c_key);
	}

	/**
	 * Set value of X5c_Key
	 * @param context
	 * @param x5c_key
	 */
	public final void setX5c_Key(com.mendix.systemwideinterfaces.core.IContext context, auth0.proxies.X5c x5c_key)
	{
		if (x5c_key == null)
			getMendixObject().setValue(context, MemberNames.X5c_Key.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.X5c_Key.toString(), x5c_key.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return keyMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final auth0.proxies.Key that = (auth0.proxies.Key) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Auth0.Key";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
