// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package auth0.proxies;

public class LogoutHelper
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject logoutHelperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Auth0.LogoutHelper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ClientId("ClientId"),
		Domain("Domain"),
		ReturnUrl("ReturnUrl");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public LogoutHelper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Auth0.LogoutHelper"));
	}

	protected LogoutHelper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject logoutHelperMendixObject)
	{
		if (logoutHelperMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Auth0.LogoutHelper", logoutHelperMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Auth0.LogoutHelper");

		this.logoutHelperMendixObject = logoutHelperMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'LogoutHelper.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static auth0.proxies.LogoutHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return auth0.proxies.LogoutHelper.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static auth0.proxies.LogoutHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new auth0.proxies.LogoutHelper(context, mendixObject);
	}

	public static auth0.proxies.LogoutHelper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return auth0.proxies.LogoutHelper.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of ClientId
	 */
	public final java.lang.String getClientId()
	{
		return getClientId(getContext());
	}

	/**
	 * @param context
	 * @return value of ClientId
	 */
	public final java.lang.String getClientId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ClientId.toString());
	}

	/**
	 * Set value of ClientId
	 * @param clientid
	 */
	public final void setClientId(java.lang.String clientid)
	{
		setClientId(getContext(), clientid);
	}

	/**
	 * Set value of ClientId
	 * @param context
	 * @param clientid
	 */
	public final void setClientId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String clientid)
	{
		getMendixObject().setValue(context, MemberNames.ClientId.toString(), clientid);
	}

	/**
	 * @return value of Domain
	 */
	public final java.lang.String getDomain()
	{
		return getDomain(getContext());
	}

	/**
	 * @param context
	 * @return value of Domain
	 */
	public final java.lang.String getDomain(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Domain.toString());
	}

	/**
	 * Set value of Domain
	 * @param domain
	 */
	public final void setDomain(java.lang.String domain)
	{
		setDomain(getContext(), domain);
	}

	/**
	 * Set value of Domain
	 * @param context
	 * @param domain
	 */
	public final void setDomain(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String domain)
	{
		getMendixObject().setValue(context, MemberNames.Domain.toString(), domain);
	}

	/**
	 * @return value of ReturnUrl
	 */
	public final java.lang.String getReturnUrl()
	{
		return getReturnUrl(getContext());
	}

	/**
	 * @param context
	 * @return value of ReturnUrl
	 */
	public final java.lang.String getReturnUrl(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ReturnUrl.toString());
	}

	/**
	 * Set value of ReturnUrl
	 * @param returnurl
	 */
	public final void setReturnUrl(java.lang.String returnurl)
	{
		setReturnUrl(getContext(), returnurl);
	}

	/**
	 * Set value of ReturnUrl
	 * @param context
	 * @param returnurl
	 */
	public final void setReturnUrl(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String returnurl)
	{
		getMendixObject().setValue(context, MemberNames.ReturnUrl.toString(), returnurl);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return logoutHelperMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final auth0.proxies.LogoutHelper that = (auth0.proxies.LogoutHelper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Auth0.LogoutHelper";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
