// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package auth0.proxies;

public class X5c
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject x5cMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Auth0.X5c";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		X5c_Key("Auth0.X5c_Key");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public X5c(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Auth0.X5c"));
	}

	protected X5c(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject x5cMendixObject)
	{
		if (x5cMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Auth0.X5c", x5cMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Auth0.X5c");

		this.x5cMendixObject = x5cMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'X5c.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static auth0.proxies.X5c initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return auth0.proxies.X5c.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static auth0.proxies.X5c initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new auth0.proxies.X5c(context, mendixObject);
	}

	public static auth0.proxies.X5c load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return auth0.proxies.X5c.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of X5c_Key
	 */
	public final auth0.proxies.Key getX5c_Key() throws com.mendix.core.CoreException
	{
		return getX5c_Key(getContext());
	}

	/**
	 * @param context
	 * @return value of X5c_Key
	 */
	public final auth0.proxies.Key getX5c_Key(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		auth0.proxies.Key result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.X5c_Key.toString());
		if (identifier != null)
			result = auth0.proxies.Key.load(context, identifier);
		return result;
	}

	/**
	 * Set value of X5c_Key
	 * @param x5c_key
	 */
	public final void setX5c_Key(auth0.proxies.Key x5c_key)
	{
		setX5c_Key(getContext(), x5c_key);
	}

	/**
	 * Set value of X5c_Key
	 * @param context
	 * @param x5c_key
	 */
	public final void setX5c_Key(com.mendix.systemwideinterfaces.core.IContext context, auth0.proxies.Key x5c_key)
	{
		if (x5c_key == null)
			getMendixObject().setValue(context, MemberNames.X5c_Key.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.X5c_Key.toString(), x5c_key.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return x5cMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final auth0.proxies.X5c that = (auth0.proxies.X5c) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Auth0.X5c";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
