// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package auth0.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import administration.proxies.Account;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class AddUserWithPassword extends CustomJavaAction<IMendixObject>
{
	private java.lang.String password;
	private java.util.List<IMendixObject> __roles;
	private java.util.List<system.proxies.UserRole> roles;
	private java.lang.String name;

	public AddUserWithPassword(IContext context, java.lang.String password, java.util.List<IMendixObject> roles, java.lang.String name)
	{
		super(context);
		this.password = password;
		this.__roles = roles;
		this.name = name;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		this.roles = new java.util.ArrayList<system.proxies.UserRole>();
		if (__roles != null)
			for (IMendixObject __rolesElement : __roles)
				this.roles.add(system.proxies.UserRole.initialize(getContext(), __rolesElement));

		// BEGIN USER CODE
		IContext context = Core.createSystemContext();
		Account account = new Account(context);
		account.setName(context, name);
		account.setPassword(context, password);
		account.setUserRoles(context, roles);
		account.commit(context);
		return account.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "AddUserWithPassword";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
