// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package auth0.actions;

import org.passay.CharacterRule;
import org.passay.EnglishCharacterData;
import org.passay.PasswordGenerator;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class GenerateRandomPassword extends CustomJavaAction<java.lang.String>
{
	private java.lang.Long length;

	public GenerateRandomPassword(IContext context, java.lang.Long length)
	{
		super(context);
		this.length = length;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		CharacterRule digits = new CharacterRule(EnglishCharacterData.Digit);
		digits.setNumberOfCharacters(3);
		CharacterRule lower = new CharacterRule(EnglishCharacterData.LowerCase);
		lower.setNumberOfCharacters(2);
		CharacterRule upper = new CharacterRule(EnglishCharacterData.UpperCase);
		upper.setNumberOfCharacters(2);
		CharacterRule special = new CharacterRule(EnglishCharacterData.Special);
		special.setNumberOfCharacters(2);
		PasswordGenerator gen = new PasswordGenerator();
	    String password = gen.generatePassword(Math.toIntExact(length), digits, lower, upper, special);
	    return password;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GenerateRandomPassword";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
