// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package auth0.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class x5cToPEM extends CustomJavaAction<java.lang.String>
{
	private java.lang.String x5c;

	public x5cToPEM(IContext context, java.lang.String x5c)
	{
		super(context);
		this.x5c = x5c;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		StringBuilder stringBuilder = new StringBuilder();
		stringBuilder.append("-----BEGIN CERTIFICATE-----\n");
		char[] x5cChars = x5c.toCharArray();
		
		for (int i = 0; i < x5cChars.length; i++) {
			stringBuilder.append(x5cChars[i]);
			if((i + 1) % 64 == 0) {
				stringBuilder.append('\n');
			}
		}
		
		stringBuilder.append("\n-----END CERTIFICATE-----");
		return stringBuilder.toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "x5cToPEM";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
