// This file was generated by Mendix Modeler 7.23.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package auth0.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the Auth0 module

	public static java.lang.String getAPPLICATION_URL()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("Auth0.APPLICATION_URL");
	}

	public static java.lang.String getCLIENT_ID()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("Auth0.CLIENT_ID");
	}

	public static java.lang.String getCLIENT_SECRET()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("Auth0.CLIENT_SECRET");
	}

	public static java.lang.String getDOMAIN_AUTH()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("Auth0.DOMAIN_AUTH");
	}

	public static java.lang.String getDOMAIN_CALLBACK()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("Auth0.DOMAIN_CALLBACK");
	}
}