// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package jwt.proxies;

public class JWT
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject jWTMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "JWT.JWT";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		iss("iss"),
		sub("sub"),
		exp("exp"),
		nbf("nbf"),
		iat("iat"),
		jti("jti"),
		kid("kid");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public JWT(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "JWT.JWT"));
	}

	protected JWT(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject jWTMendixObject)
	{
		if (jWTMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("JWT.JWT", jWTMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a JWT.JWT");

		this.jWTMendixObject = jWTMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'JWT.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static jwt.proxies.JWT initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return jwt.proxies.JWT.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static jwt.proxies.JWT initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new jwt.proxies.JWT(context, mendixObject);
	}

	public static jwt.proxies.JWT load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return jwt.proxies.JWT.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of iss
	 */
	public final java.lang.String getiss()
	{
		return getiss(getContext());
	}

	/**
	 * @param context
	 * @return value of iss
	 */
	public final java.lang.String getiss(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.iss.toString());
	}

	/**
	 * Set value of iss
	 * @param iss
	 */
	public final void setiss(java.lang.String iss)
	{
		setiss(getContext(), iss);
	}

	/**
	 * Set value of iss
	 * @param context
	 * @param iss
	 */
	public final void setiss(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String iss)
	{
		getMendixObject().setValue(context, MemberNames.iss.toString(), iss);
	}

	/**
	 * @return value of sub
	 */
	public final java.lang.String getsub()
	{
		return getsub(getContext());
	}

	/**
	 * @param context
	 * @return value of sub
	 */
	public final java.lang.String getsub(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.sub.toString());
	}

	/**
	 * Set value of sub
	 * @param sub
	 */
	public final void setsub(java.lang.String sub)
	{
		setsub(getContext(), sub);
	}

	/**
	 * Set value of sub
	 * @param context
	 * @param sub
	 */
	public final void setsub(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sub)
	{
		getMendixObject().setValue(context, MemberNames.sub.toString(), sub);
	}

	/**
	 * @return value of exp
	 */
	public final java.util.Date getexp()
	{
		return getexp(getContext());
	}

	/**
	 * @param context
	 * @return value of exp
	 */
	public final java.util.Date getexp(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.exp.toString());
	}

	/**
	 * Set value of exp
	 * @param exp
	 */
	public final void setexp(java.util.Date exp)
	{
		setexp(getContext(), exp);
	}

	/**
	 * Set value of exp
	 * @param context
	 * @param exp
	 */
	public final void setexp(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date exp)
	{
		getMendixObject().setValue(context, MemberNames.exp.toString(), exp);
	}

	/**
	 * @return value of nbf
	 */
	public final java.util.Date getnbf()
	{
		return getnbf(getContext());
	}

	/**
	 * @param context
	 * @return value of nbf
	 */
	public final java.util.Date getnbf(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.nbf.toString());
	}

	/**
	 * Set value of nbf
	 * @param nbf
	 */
	public final void setnbf(java.util.Date nbf)
	{
		setnbf(getContext(), nbf);
	}

	/**
	 * Set value of nbf
	 * @param context
	 * @param nbf
	 */
	public final void setnbf(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date nbf)
	{
		getMendixObject().setValue(context, MemberNames.nbf.toString(), nbf);
	}

	/**
	 * @return value of iat
	 */
	public final java.util.Date getiat()
	{
		return getiat(getContext());
	}

	/**
	 * @param context
	 * @return value of iat
	 */
	public final java.util.Date getiat(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.iat.toString());
	}

	/**
	 * Set value of iat
	 * @param iat
	 */
	public final void setiat(java.util.Date iat)
	{
		setiat(getContext(), iat);
	}

	/**
	 * Set value of iat
	 * @param context
	 * @param iat
	 */
	public final void setiat(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date iat)
	{
		getMendixObject().setValue(context, MemberNames.iat.toString(), iat);
	}

	/**
	 * @return value of jti
	 */
	public final java.lang.String getjti()
	{
		return getjti(getContext());
	}

	/**
	 * @param context
	 * @return value of jti
	 */
	public final java.lang.String getjti(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.jti.toString());
	}

	/**
	 * Set value of jti
	 * @param jti
	 */
	public final void setjti(java.lang.String jti)
	{
		setjti(getContext(), jti);
	}

	/**
	 * Set value of jti
	 * @param context
	 * @param jti
	 */
	public final void setjti(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String jti)
	{
		getMendixObject().setValue(context, MemberNames.jti.toString(), jti);
	}

	/**
	 * @return value of kid
	 */
	public final java.lang.String getkid()
	{
		return getkid(getContext());
	}

	/**
	 * @param context
	 * @return value of kid
	 */
	public final java.lang.String getkid(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.kid.toString());
	}

	/**
	 * Set value of kid
	 * @param kid
	 */
	public final void setkid(java.lang.String kid)
	{
		setkid(getContext(), kid);
	}

	/**
	 * Set value of kid
	 * @param context
	 * @param kid
	 */
	public final void setkid(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String kid)
	{
		getMendixObject().setValue(context, MemberNames.kid.toString(), kid);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return jWTMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final jwt.proxies.JWT that = (jwt.proxies.JWT) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "JWT.JWT";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
