// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package jwt.proxies;

public class JWTRSAKeyPair
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject jWTRSAKeyPairMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "JWT.JWTRSAKeyPair";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		KeyPairId("KeyPairId"),
		JWTRSAPublicKey_JWTRSAKeyPair("JWT.JWTRSAPublicKey_JWTRSAKeyPair"),
		JWTRSAPrivateKey_JWTRSAKeyPair("JWT.JWTRSAPrivateKey_JWTRSAKeyPair");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public JWTRSAKeyPair(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "JWT.JWTRSAKeyPair"));
	}

	protected JWTRSAKeyPair(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject jWTRSAKeyPairMendixObject)
	{
		if (jWTRSAKeyPairMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("JWT.JWTRSAKeyPair", jWTRSAKeyPairMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a JWT.JWTRSAKeyPair");

		this.jWTRSAKeyPairMendixObject = jWTRSAKeyPairMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'JWTRSAKeyPair.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static jwt.proxies.JWTRSAKeyPair initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return jwt.proxies.JWTRSAKeyPair.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static jwt.proxies.JWTRSAKeyPair initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new jwt.proxies.JWTRSAKeyPair(context, mendixObject);
	}

	public static jwt.proxies.JWTRSAKeyPair load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return jwt.proxies.JWTRSAKeyPair.initialize(context, mendixObject);
	}

	public static java.util.List<jwt.proxies.JWTRSAKeyPair> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<jwt.proxies.JWTRSAKeyPair> result = new java.util.ArrayList<jwt.proxies.JWTRSAKeyPair>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//JWT.JWTRSAKeyPair" + xpathConstraint))
			result.add(jwt.proxies.JWTRSAKeyPair.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of KeyPairId
	 */
	public final java.lang.Long getKeyPairId()
	{
		return getKeyPairId(getContext());
	}

	/**
	 * @param context
	 * @return value of KeyPairId
	 */
	public final java.lang.Long getKeyPairId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.KeyPairId.toString());
	}

	/**
	 * Set value of KeyPairId
	 * @param keypairid
	 */
	public final void setKeyPairId(java.lang.Long keypairid)
	{
		setKeyPairId(getContext(), keypairid);
	}

	/**
	 * Set value of KeyPairId
	 * @param context
	 * @param keypairid
	 */
	public final void setKeyPairId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long keypairid)
	{
		getMendixObject().setValue(context, MemberNames.KeyPairId.toString(), keypairid);
	}

	/**
	 * @return value of JWTRSAPublicKey_JWTRSAKeyPair
	 */
	public final jwt.proxies.JWTRSAPublicKey getJWTRSAPublicKey_JWTRSAKeyPair() throws com.mendix.core.CoreException
	{
		return getJWTRSAPublicKey_JWTRSAKeyPair(getContext());
	}

	/**
	 * @param context
	 * @return value of JWTRSAPublicKey_JWTRSAKeyPair
	 */
	public final jwt.proxies.JWTRSAPublicKey getJWTRSAPublicKey_JWTRSAKeyPair(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		jwt.proxies.JWTRSAPublicKey result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.JWTRSAPublicKey_JWTRSAKeyPair.toString());
		if (identifier != null)
			result = jwt.proxies.JWTRSAPublicKey.load(context, identifier);
		return result;
	}

	/**
	 * Set value of JWTRSAPublicKey_JWTRSAKeyPair
	 * @param jwtrsapublickey_jwtrsakeypair
	 */
	public final void setJWTRSAPublicKey_JWTRSAKeyPair(jwt.proxies.JWTRSAPublicKey jwtrsapublickey_jwtrsakeypair)
	{
		setJWTRSAPublicKey_JWTRSAKeyPair(getContext(), jwtrsapublickey_jwtrsakeypair);
	}

	/**
	 * Set value of JWTRSAPublicKey_JWTRSAKeyPair
	 * @param context
	 * @param jwtrsapublickey_jwtrsakeypair
	 */
	public final void setJWTRSAPublicKey_JWTRSAKeyPair(com.mendix.systemwideinterfaces.core.IContext context, jwt.proxies.JWTRSAPublicKey jwtrsapublickey_jwtrsakeypair)
	{
		if (jwtrsapublickey_jwtrsakeypair == null)
			getMendixObject().setValue(context, MemberNames.JWTRSAPublicKey_JWTRSAKeyPair.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.JWTRSAPublicKey_JWTRSAKeyPair.toString(), jwtrsapublickey_jwtrsakeypair.getMendixObject().getId());
	}

	/**
	 * @return value of JWTRSAPrivateKey_JWTRSAKeyPair
	 */
	public final jwt.proxies.JWTRSAPrivateKey getJWTRSAPrivateKey_JWTRSAKeyPair() throws com.mendix.core.CoreException
	{
		return getJWTRSAPrivateKey_JWTRSAKeyPair(getContext());
	}

	/**
	 * @param context
	 * @return value of JWTRSAPrivateKey_JWTRSAKeyPair
	 */
	public final jwt.proxies.JWTRSAPrivateKey getJWTRSAPrivateKey_JWTRSAKeyPair(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		jwt.proxies.JWTRSAPrivateKey result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.JWTRSAPrivateKey_JWTRSAKeyPair.toString());
		if (identifier != null)
			result = jwt.proxies.JWTRSAPrivateKey.load(context, identifier);
		return result;
	}

	/**
	 * Set value of JWTRSAPrivateKey_JWTRSAKeyPair
	 * @param jwtrsaprivatekey_jwtrsakeypair
	 */
	public final void setJWTRSAPrivateKey_JWTRSAKeyPair(jwt.proxies.JWTRSAPrivateKey jwtrsaprivatekey_jwtrsakeypair)
	{
		setJWTRSAPrivateKey_JWTRSAKeyPair(getContext(), jwtrsaprivatekey_jwtrsakeypair);
	}

	/**
	 * Set value of JWTRSAPrivateKey_JWTRSAKeyPair
	 * @param context
	 * @param jwtrsaprivatekey_jwtrsakeypair
	 */
	public final void setJWTRSAPrivateKey_JWTRSAKeyPair(com.mendix.systemwideinterfaces.core.IContext context, jwt.proxies.JWTRSAPrivateKey jwtrsaprivatekey_jwtrsakeypair)
	{
		if (jwtrsaprivatekey_jwtrsakeypair == null)
			getMendixObject().setValue(context, MemberNames.JWTRSAPrivateKey_JWTRSAKeyPair.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.JWTRSAPrivateKey_JWTRSAKeyPair.toString(), jwtrsaprivatekey_jwtrsakeypair.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return jWTRSAKeyPairMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final jwt.proxies.JWTRSAKeyPair that = (jwt.proxies.JWTRSAKeyPair) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "JWT.JWTRSAKeyPair";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
