// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package jwt.proxies;

public class JWTRSAPublicKey extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "JWT.JWTRSAPublicKey";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		JWTRSAPublicKey_JWTRSAKeyPair("JWT.JWTRSAPublicKey_JWTRSAKeyPair");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public JWTRSAPublicKey(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "JWT.JWTRSAPublicKey"));
	}

	protected JWTRSAPublicKey(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject jWTRSAPublicKeyMendixObject)
	{
		super(context, jWTRSAPublicKeyMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("JWT.JWTRSAPublicKey", jWTRSAPublicKeyMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a JWT.JWTRSAPublicKey");
	}

	/**
	 * @deprecated Use 'JWTRSAPublicKey.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static jwt.proxies.JWTRSAPublicKey initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return jwt.proxies.JWTRSAPublicKey.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static jwt.proxies.JWTRSAPublicKey initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		if (com.mendix.core.Core.isSubClassOf("Auth0.PublicKey", mendixObject.getType()))
			return auth0.proxies.PublicKey.initialize(context, mendixObject);

		return new jwt.proxies.JWTRSAPublicKey(context, mendixObject);
	}

	public static jwt.proxies.JWTRSAPublicKey load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return jwt.proxies.JWTRSAPublicKey.initialize(context, mendixObject);
	}

	public static java.util.List<? extends jwt.proxies.JWTRSAPublicKey> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<jwt.proxies.JWTRSAPublicKey> result = new java.util.ArrayList<jwt.proxies.JWTRSAPublicKey>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//JWT.JWTRSAPublicKey" + xpathConstraint))
			result.add(jwt.proxies.JWTRSAPublicKey.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of JWTRSAPublicKey_JWTRSAKeyPair
	 */
	public final jwt.proxies.JWTRSAKeyPair getJWTRSAPublicKey_JWTRSAKeyPair() throws com.mendix.core.CoreException
	{
		return getJWTRSAPublicKey_JWTRSAKeyPair(getContext());
	}

	/**
	 * @param context
	 * @return value of JWTRSAPublicKey_JWTRSAKeyPair
	 */
	public final jwt.proxies.JWTRSAKeyPair getJWTRSAPublicKey_JWTRSAKeyPair(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		jwt.proxies.JWTRSAKeyPair result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.JWTRSAPublicKey_JWTRSAKeyPair.toString());
		if (identifier != null)
			result = jwt.proxies.JWTRSAKeyPair.load(context, identifier);
		return result;
	}

	/**
	 * Set value of JWTRSAPublicKey_JWTRSAKeyPair
	 * @param jwtrsapublickey_jwtrsakeypair
	 */
	public final void setJWTRSAPublicKey_JWTRSAKeyPair(jwt.proxies.JWTRSAKeyPair jwtrsapublickey_jwtrsakeypair)
	{
		setJWTRSAPublicKey_JWTRSAKeyPair(getContext(), jwtrsapublickey_jwtrsakeypair);
	}

	/**
	 * Set value of JWTRSAPublicKey_JWTRSAKeyPair
	 * @param context
	 * @param jwtrsapublickey_jwtrsakeypair
	 */
	public final void setJWTRSAPublicKey_JWTRSAKeyPair(com.mendix.systemwideinterfaces.core.IContext context, jwt.proxies.JWTRSAKeyPair jwtrsapublickey_jwtrsakeypair)
	{
		if (jwtrsapublickey_jwtrsakeypair == null)
			getMendixObject().setValue(context, MemberNames.JWTRSAPublicKey_JWTRSAKeyPair.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.JWTRSAPublicKey_JWTRSAKeyPair.toString(), jwtrsapublickey_jwtrsakeypair.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final jwt.proxies.JWTRSAPublicKey that = (jwt.proxies.JWTRSAPublicKey) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "JWT.JWTRSAPublicKey";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
