// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package jwt.proxies;

public class PublicClaimResponse extends jwt.proxies.PublicClaim
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "JWT.PublicClaimResponse";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ValueBoolean("ValueBoolean"),
		ValueDateTime("ValueDateTime"),
		ValueInteger("ValueInteger"),
		ValueLong("ValueLong"),
		ValueDecimal("ValueDecimal"),
		ValueString("ValueString"),
		Claim("Claim"),
		Claim_JWT("JWT.Claim_JWT");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public PublicClaimResponse(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "JWT.PublicClaimResponse"));
	}

	protected PublicClaimResponse(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject publicClaimResponseMendixObject)
	{
		super(context, publicClaimResponseMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("JWT.PublicClaimResponse", publicClaimResponseMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a JWT.PublicClaimResponse");
	}

	/**
	 * @deprecated Use 'PublicClaimResponse.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static jwt.proxies.PublicClaimResponse initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return jwt.proxies.PublicClaimResponse.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static jwt.proxies.PublicClaimResponse initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new jwt.proxies.PublicClaimResponse(context, mendixObject);
	}

	public static jwt.proxies.PublicClaimResponse load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return jwt.proxies.PublicClaimResponse.initialize(context, mendixObject);
	}

	/**
	 * @return value of ValueBoolean
	 */
	public final java.lang.Boolean getValueBoolean()
	{
		return getValueBoolean(getContext());
	}

	/**
	 * @param context
	 * @return value of ValueBoolean
	 */
	public final java.lang.Boolean getValueBoolean(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ValueBoolean.toString());
	}

	/**
	 * Set value of ValueBoolean
	 * @param valueboolean
	 */
	public final void setValueBoolean(java.lang.Boolean valueboolean)
	{
		setValueBoolean(getContext(), valueboolean);
	}

	/**
	 * Set value of ValueBoolean
	 * @param context
	 * @param valueboolean
	 */
	public final void setValueBoolean(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean valueboolean)
	{
		getMendixObject().setValue(context, MemberNames.ValueBoolean.toString(), valueboolean);
	}

	/**
	 * @return value of ValueDateTime
	 */
	public final java.util.Date getValueDateTime()
	{
		return getValueDateTime(getContext());
	}

	/**
	 * @param context
	 * @return value of ValueDateTime
	 */
	public final java.util.Date getValueDateTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.ValueDateTime.toString());
	}

	/**
	 * Set value of ValueDateTime
	 * @param valuedatetime
	 */
	public final void setValueDateTime(java.util.Date valuedatetime)
	{
		setValueDateTime(getContext(), valuedatetime);
	}

	/**
	 * Set value of ValueDateTime
	 * @param context
	 * @param valuedatetime
	 */
	public final void setValueDateTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date valuedatetime)
	{
		getMendixObject().setValue(context, MemberNames.ValueDateTime.toString(), valuedatetime);
	}

	/**
	 * @return value of ValueInteger
	 */
	public final java.lang.Integer getValueInteger()
	{
		return getValueInteger(getContext());
	}

	/**
	 * @param context
	 * @return value of ValueInteger
	 */
	public final java.lang.Integer getValueInteger(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ValueInteger.toString());
	}

	/**
	 * Set value of ValueInteger
	 * @param valueinteger
	 */
	public final void setValueInteger(java.lang.Integer valueinteger)
	{
		setValueInteger(getContext(), valueinteger);
	}

	/**
	 * Set value of ValueInteger
	 * @param context
	 * @param valueinteger
	 */
	public final void setValueInteger(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer valueinteger)
	{
		getMendixObject().setValue(context, MemberNames.ValueInteger.toString(), valueinteger);
	}

	/**
	 * @return value of ValueLong
	 */
	public final java.lang.Long getValueLong()
	{
		return getValueLong(getContext());
	}

	/**
	 * @param context
	 * @return value of ValueLong
	 */
	public final java.lang.Long getValueLong(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.ValueLong.toString());
	}

	/**
	 * Set value of ValueLong
	 * @param valuelong
	 */
	public final void setValueLong(java.lang.Long valuelong)
	{
		setValueLong(getContext(), valuelong);
	}

	/**
	 * Set value of ValueLong
	 * @param context
	 * @param valuelong
	 */
	public final void setValueLong(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long valuelong)
	{
		getMendixObject().setValue(context, MemberNames.ValueLong.toString(), valuelong);
	}

	/**
	 * @return value of ValueDecimal
	 */
	public final java.math.BigDecimal getValueDecimal()
	{
		return getValueDecimal(getContext());
	}

	/**
	 * @param context
	 * @return value of ValueDecimal
	 */
	public final java.math.BigDecimal getValueDecimal(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.ValueDecimal.toString());
	}

	/**
	 * Set value of ValueDecimal
	 * @param valuedecimal
	 */
	public final void setValueDecimal(java.math.BigDecimal valuedecimal)
	{
		setValueDecimal(getContext(), valuedecimal);
	}

	/**
	 * Set value of ValueDecimal
	 * @param context
	 * @param valuedecimal
	 */
	public final void setValueDecimal(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal valuedecimal)
	{
		getMendixObject().setValue(context, MemberNames.ValueDecimal.toString(), valuedecimal);
	}

	/**
	 * @return value of ValueString
	 */
	public final java.lang.String getValueString()
	{
		return getValueString(getContext());
	}

	/**
	 * @param context
	 * @return value of ValueString
	 */
	public final java.lang.String getValueString(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ValueString.toString());
	}

	/**
	 * Set value of ValueString
	 * @param valuestring
	 */
	public final void setValueString(java.lang.String valuestring)
	{
		setValueString(getContext(), valuestring);
	}

	/**
	 * Set value of ValueString
	 * @param context
	 * @param valuestring
	 */
	public final void setValueString(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String valuestring)
	{
		getMendixObject().setValue(context, MemberNames.ValueString.toString(), valuestring);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final jwt.proxies.PublicClaimResponse that = (jwt.proxies.PublicClaimResponse) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "JWT.PublicClaimResponse";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
