// This file was generated by Mendix Modeler 7.23.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package viewapp.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the ViewApp module

	public static java.lang.String getAPI_AUDIENCE()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("ViewApp.API_AUDIENCE");
	}

	public static boolean getSHOW_BREAKPOINTS()
	{
		return (java.lang.Boolean)Core.getConfiguration().getConstantValue("ViewApp.SHOW_BREAKPOINTS");
	}
}