// This file was generated by Mendix Modeler 7.23.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package invoiceapi.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the InvoiceAPI module
	public static java.util.List<invoiceapi.proxies.Invoice> invoice_Get_All(IContext context, system.proxies.HttpRequest _httpRequest, system.proxies.HttpResponse _httpResponse)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("HttpRequest", _httpRequest == null ? null : _httpRequest.getMendixObject());
			params.put("HttpResponse", _httpResponse == null ? null : _httpResponse.getMendixObject());
			java.util.List<IMendixObject> objs = Core.execute(context, "InvoiceAPI.Invoice_Get_All", params);
			java.util.List<invoiceapi.proxies.Invoice> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<invoiceapi.proxies.Invoice>();
				for (IMendixObject obj : objs)
					result.add(invoiceapi.proxies.Invoice.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static invoiceapi.proxies.Invoice invoice_Get_ByKey(IContext context, system.proxies.HttpResponse _httpResponse, java.lang.Long _invoiceid, system.proxies.HttpRequest _httpRequest)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("HttpResponse", _httpResponse == null ? null : _httpResponse.getMendixObject());
			params.put("invoiceid", _invoiceid);
			params.put("HttpRequest", _httpRequest == null ? null : _httpRequest.getMendixObject());
			IMendixObject result = (IMendixObject)Core.execute(context, "InvoiceAPI.Invoice_Get_ByKey", params);
			return result == null ? null : invoiceapi.proxies.Invoice.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void invoice_Post(IContext context, system.proxies.HttpResponse _httpResponse, invoiceapi.proxies.Invoice _body, system.proxies.HttpRequest _httpRequest)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("HttpResponse", _httpResponse == null ? null : _httpResponse.getMendixObject());
			params.put("body", _body == null ? null : _body.getMendixObject());
			params.put("HttpRequest", _httpRequest == null ? null : _httpRequest.getMendixObject());
			Core.execute(context, "InvoiceAPI.Invoice_Post", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.lang.String iVK_GetTokenFromHTTPRequest(IContext context, system.proxies.HttpRequest _httpRequest)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("HttpRequest", _httpRequest == null ? null : _httpRequest.getMendixObject());
			return (java.lang.String)Core.execute(context, "InvoiceAPI.IVK_GetTokenFromHTTPRequest", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static system.proxies.User iVK_GetUserFromHTTPRequest(IContext context, system.proxies.HttpRequest _httpRequest)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("HttpRequest", _httpRequest == null ? null : _httpRequest.getMendixObject());
			IMendixObject result = (IMendixObject)Core.execute(context, "InvoiceAPI.IVK_GetUserFromHTTPRequest", params);
			return result == null ? null : system.proxies.User.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean iVK_ValidateScope(IContext context, jwt.proxies.JWT _jWT, invoiceapi.proxies.ENU_Scopes _scope)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("JWT", _jWT == null ? null : _jWT.getMendixObject());
			params.put("Scope", _scope == null ? null : _scope.name());
			return (java.lang.Boolean)Core.execute(context, "InvoiceAPI.IVK_ValidateScope", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}