// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package viewapp.proxies;

public class InvoiceView
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject invoiceViewMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "ViewApp.InvoiceView";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		InvoiceId("InvoiceId"),
		TotalAmount("TotalAmount"),
		InvoiceDate("InvoiceDate");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public InvoiceView(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "ViewApp.InvoiceView"));
	}

	protected InvoiceView(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject invoiceViewMendixObject)
	{
		if (invoiceViewMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("ViewApp.InvoiceView", invoiceViewMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a ViewApp.InvoiceView");

		this.invoiceViewMendixObject = invoiceViewMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'InvoiceView.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static viewapp.proxies.InvoiceView initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return viewapp.proxies.InvoiceView.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static viewapp.proxies.InvoiceView initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new viewapp.proxies.InvoiceView(context, mendixObject);
	}

	public static viewapp.proxies.InvoiceView load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return viewapp.proxies.InvoiceView.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of InvoiceId
	 */
	public final java.lang.Integer getInvoiceId()
	{
		return getInvoiceId(getContext());
	}

	/**
	 * @param context
	 * @return value of InvoiceId
	 */
	public final java.lang.Integer getInvoiceId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.InvoiceId.toString());
	}

	/**
	 * Set value of InvoiceId
	 * @param invoiceid
	 */
	public final void setInvoiceId(java.lang.Integer invoiceid)
	{
		setInvoiceId(getContext(), invoiceid);
	}

	/**
	 * Set value of InvoiceId
	 * @param context
	 * @param invoiceid
	 */
	public final void setInvoiceId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer invoiceid)
	{
		getMendixObject().setValue(context, MemberNames.InvoiceId.toString(), invoiceid);
	}

	/**
	 * @return value of TotalAmount
	 */
	public final java.lang.Integer getTotalAmount()
	{
		return getTotalAmount(getContext());
	}

	/**
	 * @param context
	 * @return value of TotalAmount
	 */
	public final java.lang.Integer getTotalAmount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.TotalAmount.toString());
	}

	/**
	 * Set value of TotalAmount
	 * @param totalamount
	 */
	public final void setTotalAmount(java.lang.Integer totalamount)
	{
		setTotalAmount(getContext(), totalamount);
	}

	/**
	 * Set value of TotalAmount
	 * @param context
	 * @param totalamount
	 */
	public final void setTotalAmount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer totalamount)
	{
		getMendixObject().setValue(context, MemberNames.TotalAmount.toString(), totalamount);
	}

	/**
	 * @return value of InvoiceDate
	 */
	public final java.util.Date getInvoiceDate()
	{
		return getInvoiceDate(getContext());
	}

	/**
	 * @param context
	 * @return value of InvoiceDate
	 */
	public final java.util.Date getInvoiceDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.InvoiceDate.toString());
	}

	/**
	 * Set value of InvoiceDate
	 * @param invoicedate
	 */
	public final void setInvoiceDate(java.util.Date invoicedate)
	{
		setInvoiceDate(getContext(), invoicedate);
	}

	/**
	 * Set value of InvoiceDate
	 * @param context
	 * @param invoicedate
	 */
	public final void setInvoiceDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date invoicedate)
	{
		getMendixObject().setValue(context, MemberNames.InvoiceDate.toString(), invoicedate);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return invoiceViewMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final viewapp.proxies.InvoiceView that = (viewapp.proxies.InvoiceView) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "ViewApp.InvoiceView";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
