// This file was generated by Mendix Modeler 7.23.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package jwt.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the JWT module

	public static java.lang.String getLOGNODE()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("JWT.LOGNODE");
	}
}