// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the code between BEGIN USER CODE and END USER CODE
// Other code you write will be lost the next time you deploy the project.

/**
 * @param {string} returnUrl
 * @param {string} clientId
 * @param {string} domain
 * @returns {boolean}
 */
function LogoutUser(returnUrl, clientId, domain) {
	// BEGIN USER CODE
	mx.session.logout();
	window.location.replace("https://" + domain + "/v2/logout?returnTo=" + returnUrl + "&client_id=" + clientId);
	return true;
	// END USER CODE
}